# Generated by Django 3.0.1 on 2019-12-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_board_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='owner',
            field=models.CharField(default='site_admin@bringo.com', max_length=255),
            preserve_default=False,
        ),
    ]
